const AG_GRID_LOCALE_FR = {
    
    selectAll: '(Tout s\u00e9lectionner) ',
    selectAllSearchResults: '(S\u00e9lectionnez tous les r\u00e9sultats de la recherche) ',
    searchOoo: 'Rechercher... ',
    blanks: '(Blancs) ',
    noMatches: 'Pas de correspondance ',
    filterOoo: 'Filtre... ',
    equals: '\u00c9quivaut \u00e0 ',
    notEqual: 'In\u00e9gal ',
    blank: 'Vierge ',
    notBlank: 'Non vide ',
    empty: 'Choisissez-en un ',
    lessThan: 'Moins que ',
    greaterThan: 'Plus grand que ',
    lessThanOrEqual: 'Moins ou \u00e9gal ',
    greaterThanOrEqual: 'Meilleur que ou \u00e9gal ',
    inRange: 'Dans la gamme ',
    inRangeStart: '\u00e0 partir de ',
    inRangeEnd: 'pour ',
    contains: 'Contenir ',
    notContains: 'Ne contient pas ',
    startsWith: 'Commence avec ',
    endsWith: 'Se termine par ',
    dateFormatOoo: 'yyyy-mm-dd ',
    andCondition: 'ET ',
    orCondition: 'OU ',
    applyFilter: 'Appliquer ',
    resetFilter: 'R\u00e9initialiser ',
    clearFilter: 'D\u00e9gager ',
    cancelFilter: 'Annuler ',
    textFilter: 'Filtre de texte ',
    numberFilter: 'Filtre de num\u00e9ro ',
    dateFilter: 'Filtre de date ',
    setFilter: 'R\u00e9gler le filtre ',
    columns: 'Colonnes ',
    filters: 'Filtres ',
    pivotMode: 'Mode pivot ',
    groups: 'Groupes de lignes ',
    rowGroupColumnsEmptyMessage: 'Faites glisser ici pour d\u00e9finir des groupes de lignes ',
    values: 'Valeurs ',
    valueColumnsEmptyMessage: 'Glisser ici pour regrouper ',
    pivots: '\u00c9tiquettes de colonne ',
    pivotColumnsEmptyMessage: 'Faites glisser ici pour d\u00e9finir des \u00e9tiquettes de colonne ',
    group: 'Grouper ',
    loadingOoo: 'Chargement... ',
    noRowsToShow: 'Pas de lignes \u00e0 montrer ',
    enabled: 'Autoris\u00e9',
    pinColumn: 'Pince \u00e0 broches ',
    pinLeft: 'Pin \u00e0 gauche ',
    pinRight: 'Pin \u00e0 droite ',
    noPin: 'Pas d \u00e9 pingle ',
    valueAggregation: 'Agr\u00e9gation de la valeur ',
    autosizeThiscolumn: 'Autosiser cette colonne ',
    autosizeAllColumns: 'Autosiser toutes les colonnes ',
    groupBy: 'Par groupe ',
    ungroupBy: 'Un groupe de lONU ',
    addToValues: 'Ajouter $ {variable} aux valeurs ',
    removeFromValues: 'Supprimer $ {variable} des valeurs ',
    addToLabels: 'Ajouter $ {variable} aux \u00e9tiquettes ',
    removeFromLabels: 'Supprimer $ {variable} des \u00e9tiquettes ',
    resetColumns: 'R\u00e9initialiser les colonnes ',
    expandAll: 'D\u00e9velopper tout ',
    collapseAll: 'Ferme tout ',
    copy: 'Copie ',
    ctrlC: 'Ctrl + c ',
    copyWithHeaders: 'Copier avec des en-t\u00eates ',
    copyWithHeaderGroups: 'Copier avec des groupes den-t\u00eate ',
    paste: 'P\u00e2te ',
    ctrlV: 'Ctrl + V ',
    export: 'Exportation ',
    csvExport: 'Exportation CSV ',
    excelExport: 'Exportation Excel ',
    sum: 'Somme ',
    min: 'Min ',
    max: 'Max ',
    none: ['AucunAucune'],
    count: 'Compter ',
    avg: ['Moyen Moyenne'],
    filteredRows: ['Filtr\u00e9 Filtr\u00e9e'],
    selectedRows: ['Choisi', 'Choisie'],
    totalRows: 'Total des rang\u00e9es ',
    totalAndFilteredRows: 'Lignes ',
    more: 'Suite ',
    to: 'pour ',
    of: 'de ',
    page: 'Page ',
    nextPage: 'Page suivante ',
    lastPage: 'Derni\u00e8re page ',
    firstPage: 'Premi\u00e8re page ',
    previousPage: 'Page pr\u00e9c\u00e9dente ',
    pivotColumnGroupTotals: ['Total','Totale'],
    pivotChartAndPivotMode: 'Tableau pivot et mode pivot ',
    pivotChart: 'Graphique de pivot ',
    chartRange: 'Gamme de graphiques ',
    columnChart: 'Colonne ',
    groupedColumn: 'Group\u00e9 ',
    stackedColumn: ['Empil\u00e9','Empil\u00e9e'],
    normalizedColumn: '100% empil\u00e9 ',
    barChart: 'Bar ',
    groupedBar: 'Group\u00e9 ',
    stackedBar: ['Empil\u00e9', 'Empil\u00e9e'],
    normalizedBar: '100% empil\u00e9 ',
    pieChart: 'Tarte ',
    pie: 'Tarte ',
    doughnut: 'Donut ',
    line: 'Ligne ',
    xyChart: 'X y (dispersion) ',
    scatter: 'Dispersion ',
    bubble: 'Bulle ',
    areaChart: 'R\u00e9gion ',
    area: 'R\u00e9gion ',
    stackedArea: ['Empil\u00e9', 'Empil\u00e9e'],
    normalizedArea: '100% empil\u00e9 ',
    histogramChart: 'Histogramme ',
    pivotChartTitle: 'Graphique de pivot ',
    rangeChartTitle: 'Graphique de gamme ',
    settings: 'R\u00e9glages ',
    data: ['Donn\u00e9s', 'Donn\u00e9es'],
    format: 'Format ',
    categories: 'Cat\u00e9gories ',
    defaultCategory: ['(Aucun)', '(Aucune)'],
    series: 'S\u00e9ries ',
    xyValues: 'X Y valeurs ',
    paired: 'Mode jumel\u00e9 ',
    axis: 'Axe ',
    navigator: ['Navigateur', 'Navigatrice'],
    color: 'Couleur ',
    thickness: '\u00c9paisseur ',
    xType: 'Type X ',
    automatic: 'Automatique ',
    category: 'Cat\u00e9gorie ',
    number: 'Nombre ',
    time: 'Temps ',
    xRotation: 'X rotation ',
    yRotation: 'Y rotation ',
    ticks: 'Ticks ',
    width: 'Largeur ',
    height: 'Hauteur ',
    length: 'Longueur ',
    padding: 'Rembourrage ',
    spacing: 'Espacement ',
    chart: 'Graphique ',
    title: 'Titre ',
    titlePlaceholder: 'Titre du graphique - Double-cliquez pour modifier ',
    background: 'Contexte ',
    font: 'Police de caract\u00e8re ',
    top: 'Haut ',
    right: ['Droit', 'Droite'],
    bottom: 'Bas ',
    left: 'La gauche ',
    labels: '\u00c9tiquettes ',
    size: 'Taille ',
    minSize: 'Taille minimale ',
    maxSize: 'Taille maximum ',
    legend: 'L\u00e9gende ',
    position: 'Position ',
    markerSize: 'Taille de marqueur ',
    markerStroke: 'Coup de rep\u00e8re ',
    markerPadding: 'Pav\u00e9 de marqueur ',
    itemSpacing: 'Espacement des articles ',
    itemPaddingX: 'Article Padding x ',
    itemPaddingY: 'Article Padding Y ',
    layoutHorizontalSpacing: 'Espacement horizontal ',
    layoutVerticalSpacing: 'Espacement vertical ',
    strokeWidth: 'Largeur du trait ',
    offset: 'D\u00e9calage ',
    offsets: 'Compensation ',
    tooltips: 'Info ',
    callout: 'Faire appel \u00e0 ',
    markers: ['Marqueurs', 'Marqueuses'],
    shadow: 'Ombre ',
    blur: 'Se brouiller ',
    xOffset: 'X offset ',
    yOffset: 'Y offset ',
    lineWidth: 'Largeur de ligne ',
    normal: ['Normal', 'Normale'],
    bold: ['Audacieux', 'Audacieuse'],
    italic: 'Italique ',
    boldItalic: 'Gras italique ',
    predefined: ['Pr\u00e9d\u00e9fini', 'Pr\u00e9d\u00e9finie'],
    fillOpacity: 'Remplir lopacit\u00e9 ',
    strokeOpacity: 'Ligne dopacit\u00e9 ',
    histogramBinCount: 'Comptage des bacs ',
    columnGroup: 'Colonne ',
    barGroup: 'Bar ',
    pieGroup: 'Tarte ',
    lineGroup: 'Ligne ',
    scatterGroup: 'X y (dispersion) ',
    areaGroup: 'R\u00e9gion ',
    histogramGroup: 'Histogramme ',
    groupedColumnTooltip: 'Group\u00e9 ',
    stackedColumnTooltip: ['Empil\u00e9', 'Empil\u00e9e'],
    normalizedColumnTooltip: '100% empil\u00e9 ',
    groupedBarTooltip: 'Group\u00e9 ',
    stackedBarTooltip: ['Empil\u00e9', 'Empil\u00e9e'],
    normalizedBarTooltip: '100% empil\u00e9 ',
    pieTooltip: 'Tarte ',
    doughnutTooltip: 'Donut ',
    lineTooltip: 'Ligne ',
    groupedAreaTooltip: 'R\u00e9gion ',
    stackedAreaTooltip: ['Empil\u00e9', 'Empil\u00e9e'],
    normalizedAreaTooltip: '100% empil\u00e9 ',
    scatterTooltip: 'Dispersion ',
    bubbleTooltip: 'Bulle ',
    histogramTooltip: 'Histogramme ',
    noDataToChart: 'Aucune donn\u00e9e disponible pour \u00eatre cartographi\u00e9e. ',
    pivotChartRequiresPivotMode: 'Le graphique de pivot n\u00e9cessite le mode de pivotement activ\u00e9. ',
    chartSettingsToolbarTooltip: 'Menu ',
    chartLinkToolbarTooltip: 'Li\u00e9 \u00e0 la grille ',
    chartUnlinkToolbarTooltip: 'Disp\u00e9dit\u00e9 de la grille ',
    chartDownloadToolbarTooltip: 'Tableau de t\u00e9l\u00e9chargement ',
    ariaHidden: ['cach\u00e9', 'cach\u00e9e'],
    ariaVisible: 'visible ',
    ariaChecked: 'v\u00e9rifi\u00e9 ',
    ariaUnchecked: 'non contr\u00f4l\u00e9 ',
    ariaIndeterminate: ['ind\u00e9termin\u00e9', 'ind\u00e9termin\u00e9e'],
    ariaDefaultListName: 'Lister ',
    ariaColumnSelectAll: 'Toggle S\u00e9lectionnez toutes les colonnes ',
    ariaInputEditor: '\u00c9diteur dentr\u00e9e ',
    ariaDateFilterInput: 'Entr\u00e9e de filtre de date ',
    ariaFilterList: 'Liste de filtres ',
    ariaFilterInput: 'Entr\u00e9e de filtrage ',
    ariaFilterColumnsInput: 'Entr\u00e9e de colonnes filtrantes ',
    ariaFilterValue: 'Valeur du filtre ',
    ariaFilterFromValue: 'Filtrer de la valeur ',
    ariaFilterToValue: 'Filtrer pour valoriser ',
    ariaFilteringOperator: 'Filtrage ',
    ariaColumn: 'Colonne ',
    ariaColumnList: 'Liste de colonnes ',
    ariaColumnGroup: 'Groupe de colonnes ',
    ariaRowSelect: 'Appuyez sur Espace pour s\u00e9lectionner cette ligne ',
    ariaRowDeselect: 'Appuyez sur Espace pour d\u00e9s\u00e9lectionner cette ligne ',
    ariaRowToggleSelection: 'Appuyez sur espace pour basculer la s\u00e9lection de la ligne ',
    ariaRowSelectAll: 'Appuyez sur espace pour basculer toute la s\u00e9lection des lignes ',
    ariaToggleVisibility: 'Appuyez sur Espace pour basculer la visibilit\u00e9 ',
    ariaSearch: 'Rechercher ',
    ariaSearchFilterValues: 'Valeurs de filtre de recherche ',
    ariaRowGroupDropZonePanelLabel: 'Groupes de lignes ',
    ariaValuesDropZonePanelLabel: 'Valeurs ',
    ariaPivotDropZonePanelLabel: '\u00c9tiquettes de colonne ',
    ariaDropZoneColumnComponentDescription: 'Appuyez sur Supprimer pour supprimer ',
    ariaDropZoneColumnValueItemDescription: 'Appuyez sur ENTER pour modifier le type dagr\u00e9gation ',
    ariaLabelColumnMenu: 'Menu de colonne ',
    ariaLabelCellEditor: '\u00c9diteur de cellules ',
    ariaLabelDialog: 'Dialogue ',
    ariaLabelSelectField: 'S\u00e9lectionner le champ ',
    ariaLabelTooltip: 'Info ',
    ariaLabelContextMenu: 'Menu contextuel ',
    ariaLabelSubMenu: 'Sous-menu ',
    ariaLabelAggregationFunction: 'Fonction dagr\u00e9gation '

}